version: '1.0.0'
services:
  app:
    container_name: cheer-up-app
    restart: always
    build: .
    ports:
      - '3001:3001'
    environment:
      PORT: 3001
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: cheer-up
      NAME: ritik
      JWT_SECRET: my-jwt-secret
      WATSON_API_KEY: api-key
      SERVICE_URL: service-url
    depends_on:
      - mongo_db

  mongo_db:
    container_name: db_container
    image: mongo:latest
    volumes:
      - mongo_db:/data/db
    ports:
      - '27012:27017'

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - '8083:8081'

volumes:
  mongo_db: {}
